name: Java QA with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:

  maven-test:

    name: Build and run (unit) tests
    runs-on: ubuntu-latest

    environment:
      name: Test
      url: https://test.phexpedition.net

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
    - name: Run tests with Maven
      run: mvn -B test --file pom.xml


  maven-sonarqube:

    name: Sonarqube code analysis
    runs-on: ubuntu-latest

    environment:
      name: Test
      url: https://test.phexpedition.net

    needs: maven-test

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Run code analysis through Sonarqube with Maven
        run: mvn -B verify sonar:sonar --file pom.xml -Pcoverage -Dsonar.login=${{ secrets.SONAR_TOKEN }}
