name: Java QA with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:

  maven-validate:

    name: Validate and build
    runs-on: ubuntu-latest

    environment:
      name: Test

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
      - name: Verify with Maven
        run: mvn -B clean compile --file pom.xml

  maven-test:

    name: Run (unit) tests
    runs-on: ubuntu-latest

    environment:
      name: Test

    needs: maven-validate

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Run tests with Maven
      run: mvn -B test --file pom.xml


  maven-sonarqube:

    name: Sonarqube code analysis
    runs-on: ubuntu-latest

    environment:
      name: Test

    needs: maven-validate

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Run code analysis through Sonarqube with Maven
        run: mvn -B verify sonar:sonar --file pom.xml -Pcoverage -Dsonar.login=${{ secrets.SONAR_TOKEN }}


  deploy-test:

    name: Google Cloud - deploy to test
    runs-on: ubuntu-latest

    environment:
      name: Test
      url: https://test.phexpedition.net

    needs: [maven-test, maven-sonarqube]

    steps:
      - name: Print a variable
        run: echo "The value of my_variable is ${{ github.workspace }}"


  deploy-beta:

    name: Google Cloud - deploy to test
    runs-on: ubuntu-latest

    environment:
      name: Beta
      url: https://beta.phexpedition.net

    needs: [maven-test, maven-sonarqube, deploy-test]

    steps:
      - name: Print a variable
        run: echo "The value of my_variable is ${{ github.workspace }}"