name: Google Cloud Run deployment template

on:
  workflow_call:
    inputs:
      service_name:
        required: true
        type: string
    secrets: inherit


jobs:

  deploy-cloud-run:

    needs: [maven-test, maven-sonarqube]

    environment:
      name: Test
      url: https://test.phexpedition.net

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up GCP project and credentials
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_KEY }}
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ inputs.service_name }} \
            --source . \
            --region europe-west1 \
            --allow-unauthenticated \
            --set-env-vars AUTH_REDIRECT_URI=https://test.phexpedition.net \
            --set-secrets AUTH_CLIENT_ID=AUTH_CLIENT_ID:latest