name: Initialize Google Cloud Project

# Triggered manually in GitHub UI
on:
  workflow_dispatch:

jobs:

  setup-project:

    name: Setup Google Cloud project
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - environment: Test
            url: ${{ vars.SERVICE_URL }}
          - environment: Prod
            url: ${{ vars.SERVICE_URL }}

    environment:
      url: ${{ matrix.url }}
      name: ${{ matrix.environment }}

    steps:

      - name: Hint
        run: echo "Processing environment '${{ matrix.environment }}' with serive URL '${{ matrix.url }}'"

      #
      # Install Google Cloud SDK and authenticate against project
      #
      - name: Install gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_KEY }}

      #
      # Enable required APIs
      #
      - name: Enable API - IAM
        run: gcloud services enable iam.googleapis.com
      - name: Enable API - Cloud Resource Manager
        run: gcloud services enable cloudresourcemanager.googleapis.com

      #
      # Service accounts and roles
      #
      - name: Setup Cloud Run service account
        run: |
          gcloud iam service-accounts create appuser \
            --project ${{ secrets.GOOGLE_PROJECT }} \
            --display-name "App Service Account"
      - name: Define roles for Cloud Run service account
        run: |
          gcloud projects add-iam-policy-binding ${{ secrets.GOOGLE_PROJECT }} \
            --member "serviceAccount:appuser@${{ secrets.GOOGLE_PROJECT }}.iam.gserviceaccount.com" \
            --role "roles/cloud.run.invoker" \
            --role "roles/datastore.owner"
