#
# This is an action intended to further setup your Google Cloud project representing
# a stage (such as test, production).
#
# It requires:
# - you have (manually) created a Google Cloud project per stage
# - you have set up a dedicated GitHub Actions Environment per stage
# - you have setup a dedicated Google Cloud service account in each project
#   with the roles as described in the README.md
# - each GitHub Actions Environment has the according variables and secrets
#   as described in the README.md
#

name: Initialize Google Cloud Project

# Triggered manually in GitHub UI
on:
  workflow_dispatch:

jobs:

  setup-common:

    name: Setup Google Cloud project common stuff
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - environment: Test
            url: ${{ vars.SERVICE_URL }}
          - environment: Prod
            url: ${{ vars.SERVICE_URL }}

    environment:
      url: ${{ matrix.url }}
      name: ${{ matrix.environment }}

    steps:

      - name: Hint
        run: echo "Processing environment '${{ matrix.environment }}' with service URL '${{ vars.SERVICE_URL }}'"

      #
      # Install Google Cloud SDK and authenticate against project
      #
      - name: Install gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ vars.GOOGLE_PROJECT }}

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_KEY }}

      #
      # Enable required APIs
      #
      - name: Enable API - IAM
        run: gcloud services enable iam.googleapis.com --project ${{ vars.GOOGLE_PROJECT }}
      - name: Enable API - Cloud Resource Manager
        run: gcloud services enable cloudresourcemanager.googleapis.com --project ${{ vars.GOOGLE_PROJECT }}
      - name: Enable API - Secrets Manager
        run: gcloud services enable secretmanager.googleapis.com --project ${{ vars.GOOGLE_PROJECT }}
      - name: Enable API - Cloud Run
        run: gcloud services enable run.googleapis.com --project ${{ vars.GOOGLE_PROJECT }}


      #
      # Service accounts and roles
      #
      - name: Setup Cloud Run service account
        run: |
          gcloud iam service-accounts create appuser \
            --project ${{ vars.GOOGLE_PROJECT }} \
            --display-name "App Service Account" \
            --quiet

      - name: Role - Cloud Run
        run: |
          gcloud projects add-iam-policy-binding ${{ vars.GOOGLE_PROJECT }} \
            --member "serviceAccount:appuser@${{ vars.GOOGLE_PROJECT }}.iam.gserviceaccount.com" \
            --condition None \
            --role "roles/run.invoker"
      - name: Role - Cloud Firestore Admin SDK
        run: |
          gcloud projects add-iam-policy-binding ${{ vars.GOOGLE_PROJECT }} \
            --member "serviceAccount:appuser@${{ vars.GOOGLE_PROJECT }}.iam.gserviceaccount.com" \
            --condition None \
            --role "roles/datastore.owner"
      - name: Role - access secrets from Secrets manager
        run: |
          gcloud projects add-iam-policy-binding ${{ vars.GOOGLE_PROJECT }} \
            --member "serviceAccount:appuser@${{ vars.GOOGLE_PROJECT }}.iam.gserviceaccount.com" \
            --condition None \
            --role "roles/secretmanager.secretAccessor"



  setup-test:

    name: Setup Google Cloud project test
    runs-on: ubuntu-latest

    needs: [setup-common]

    environment:
      name: Test
      url: ${{ vars.SERVICE_URL }}

    steps:

      #
      # Install Google Cloud SDK and authenticate against project
      #
      - name: Install gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ vars.GOOGLE_PROJECT }}

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_KEY }}

      #
      # Enable required APIs
      #
      - name: Enable API - Artefact Registry
        run: gcloud services enable artifactregistry.googleapis.com --project ${{ vars.GOOGLE_PROJECT }}
      - name: Enable API - Cloud Build
        run: gcloud services enable cloudbuild.googleapis.com --project ${{ vars.GOOGLE_PROJECT }}

      #
      # Roles
      #
      # Prod -> images on Test
      - name: Role - Access images from test project from prod
        run: |
          gcloud projects add-iam-policy-binding ${{ vars.GOOGLE_PROJECT }} \
            --member "serviceAccount:appuser@${{ vars.GOOGLE_PROJECT_PROD }}.iam.gserviceaccount.com" \
            --condition None \
            --role roles/compute.imageUser



  setup-prod:

    name: Setup Google Cloud project prod
    runs-on: ubuntu-latest

    needs: [setup-common]

    environment:
      name: Prod
      url: ${{ vars.SERVICE_URL }}

    steps:

      #
      # Install Google Cloud SDK and authenticate against project
      #
      - name: Install gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ vars.GOOGLE_PROJECT }}

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_KEY }}

