#
# This is an action intended to further setup your Google Cloud project representing
# a stage (such as test, production).
#
# It requires:
# - you have (manually) created a Google Cloud project per stage
# - you have set up a dedicated GitHub Actions Environment per stage
# - you have setup a dedicated Google Cloud service account in each project
#   with the roles as described in the README.md
# - each GitHub Actions Environment has the according variables and secrets
#   as described in the README.md
#

name: Initialize Google Cloud Project

# Triggered manually in GitHub UI
on:
  workflow_dispatch:

jobs:

  setup-project:

    name: Setup Google Cloud project
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - environment: Test
            url: ${{ vars.SERVICE_URL }}
          - environment: Prod
            url: ${{ vars.SERVICE_URL }}

    environment:
      url: ${{ matrix.url }}
      name: ${{ matrix.environment }}

    steps:

      - name: Hint
        run: echo "Processing environment '${{ matrix.environment }}' with service URL '${{ vars.SERVICE_URL }}'"

      #
      # Install Google Cloud SDK and authenticate against project
      #
      - name: Install gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_KEY }}

      #
      # Enable required APIs
      #
      - name: Enable API - IAM
        run: gcloud services enable iam.googleapis.com
      - name: Enable API - Cloud Resource Manager
        run: gcloud services enable cloudresourcemanager.googleapis.com

      #
      # Service accounts and roles
      #
      - name: Setup Cloud Run service account
        run: |
          gcloud iam service-accounts create appuser \
            --project ${{ secrets.GOOGLE_PROJECT }} \
            --display-name "App Service Account"

      # Roles
      - name: Role - Cloud Run
        run: |
          gcloud projects add-iam-policy-binding ${{ secrets.GOOGLE_PROJECT }} \
            --member "serviceAccount:appuser@${{ secrets.GOOGLE_PROJECT }}.iam.gserviceaccount.com" \
            --role "roles/run.invoker"
      - name: Role - Cloud Firestore Admin SDK
        run: |
          gcloud projects add-iam-policy-binding ${{ secrets.GOOGLE_PROJECT }} \
            --member "serviceAccount:appuser@${{ secrets.GOOGLE_PROJECT }}.iam.gserviceaccount.com" \
            --role "roles/datastore.owner"
