name: Initialize Google Cloud Project

on:
  workflow_dispatch:

jobs:

  setup-test:

    name: Google Cloud - setup
    runs-on: ubuntu-latest

    environment:
      name: Prod
      url: ${{ vars.SERVICE_URL }}

    steps:
      - name: Install gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GOOGLE_PROJECT }}
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GOOGLE_KEY }}
      - name: Enable API - IAM
        run: |
          gcloud services enable iam.googleapis.com
      - name: Setup Cloud Run service account
        run: |
          gcloud iam service-accounts create appuser \
            --display-name="App Service Account"
      - name: Define roles for Cloud Run service account
        run: |
          gcloud projects add-iam-policy-binding ${{ secrets.GOOGLE_PROJECT }} \
            --member "serviceAccount:appuser@${{ secrets.GOOGLE_PROJECT }}.iam.gserviceaccount.com" \
            --role "roles/cloud.run.invoker" \
            --role "roles/datastore.owner"
